stages:
  - setup
  - build_test
  - archive
.default:
  image: python:3.11
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - .cache/pip/
  before_script:
    - python --version
    - pip --version
    - mkdir -p target test-results
    - pip install --upgrade pip
    - pip install -r requirements.txt
windows_build_test:
  stage: build_test
  script:
    - powershell -Command "Write-Host 'Using PowerShell on Windows runner'"
    - powershell -Command "if (-not (Test-Path target)) { New-Item -ItemType Directory -Path target | Out-Null }"
    - powershell -Command "if (-not (Test-Path test-results)) { New-Item -ItemType Directory -Path test-results | Out-Null }"
    - powershell -Command "python -m pip install --upgrade pip"
    - powershell -Command "python -m pip install -r requirements.txt"
    - powershell -Command "python hello.py > target\output.txt"
    - powershell -Command "pytest --junitxml=test-results\results.xml"
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - target/
      - test-results/
    reports:
      junit: test-results/results.xml

